Update linter.yml

diff --git a/.github/workflows/linter.yml b/.github/workflows/linter.yml
--- a/.github/workflows/linter.yml
+++ b/.github/workflows/linter.yml
@@ -1,42 +1,73 @@
-name: Lint
+name: Lint commit
 
 on:
   push:
-    branches:
-      - main
-      - develop
-      - features/*
-      - hotfixes/*
+  pull_request:
+  merge_group:
+
+# Don't grant any access by default
+permissions: {}
 
 jobs:
-  lint:
-    name: Lint
+  commitlint:
     runs-on: ubuntu-latest
-
+    permissions:
+        contents: read
     steps:
-      - name: Checkout code
-        uses: actions/checkout@v2
-
-      - name: Install dependencies
-        uses: pnpm/action-setup@v2
+      - uses: actions/checkout@v4
         with:
-          version: 7.12.1
+          fetch-depth: 0
 
-      - name: Lint
+      - name: Check if the pull request contains a single commit
+        if: github.event_name == 'pull_request'
         run: |
-          pnpm exec eslint --ext .ts,.tsx,.js,.jsx . --fix
-          pnpm exec prettier --write '**/*.{js,jsx,ts,tsx,json,graphql,md}'
+          commit_count=${{ github.event.pull_request.commits }}
 
-      - name: Format commit message
-        uses: hades246/git-auto-commit-message@v1.1.0
+          if [ -z ${commit_count} ]; then
+            echo "[ERROR] commit_count is empty"
+            exit 1
+          fi
 
-      - name: Commit changes
+          if [[ ${commit_count} -ne 1 ]]; then
+            echo "[ERROR] This pull request contains ${commit_count} commits. Squash these commits into a single commit."
+            exit 1
+          else
+            echo "This pull request contains ${commit_count} commit."
+          fi
+
+      - name: Set commit metadata
         run: |
-          git config --local user.email "action@github.com"
-          git config --local user.name "GitHub Action"
-          git commit -am "chore: apply eslint and prettier fixes"
+          SET_INTERVAL_VALUES="true"
+          if [[ ${{ github.event_name }} == 'push' ]] || [[ ${{ github.event_name }} == 'merge_group' ]]; then
+            echo "Using default commit metadata"
+            SET_INTERVAL_VALUES="false"
+          elif [[ ${{ github.event_name }} == 'pull_request' ]]; then
+            FROM_INTERVAL_COMMITLINT=${{ github.event.pull_request.head.sha }}~${{ github.event.pull_request.commits }}
+            TO_INTERVAL_COMMITLINT=${{ github.event.pull_request.head.sha }}
+          else
+            echo "[ERROR] Event not supported when setting commit metadata"
+            exit 1
+          fi
 
-      - name: Push changes
-        uses: ad-m/github-push-action@master
-        with:
-          github_token: ${{ secrets.GITHUB_TOKEN }}
+          if [ "${SET_INTERVAL_VALUES}" == "true" ]; then
+            if [ -z "${FROM_INTERVAL_COMMITLINT}" ]; then
+              echo "[ERROR] FROM_INTERVAL_COMMITLINT is empty"
+              exit 1
+            fi
+
+            if [ -z "${TO_INTERVAL_COMMITLINT}" ]; then
+              echo "[ERROR] TO_INTERVAL_COMMITLINT is empty"
+              exit 1
+            fi
+
+            {
+              echo "FROM_INTERVAL_COMMITLINT=${FROM_INTERVAL_COMMITLINT}"
+              echo "TO_INTERVAL_COMMITLINT=${TO_INTERVAL_COMMITLINT}"
+            } >> "${GITHUB_ENV}"
+          else
+            echo "Skip updating GITHUB_ENV. SET_INTERVAL_VALUES: ${SET_INTERVAL_VALUES}"
+          fi
+
+      - name: Validate commits
+        run: |
+          make lint-commits
